# Generated by Django 5.2.12 on 2026-04-06 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_sessions', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['start_time'], name='event_sessi_start_t_530ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='session',
            index=models.Index(fields=['session_type'], name='event_sessi_session_61d244_idx'),
        ),
    ]
