# Generated by Django 5.2.12 on 2026-04-06 08:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_events_even_status_5709b6_idx_and_more'),
        ('registrations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['status'], name='registratio_status_42419d_idx'),
        ),
    ]
